# Generated by Django 5.1.1 on 2024-11-08 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_telegramuser_quiz_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='is_web_user',
            field=models.BooleanField(default=False, verbose_name='Веб-пользователь'),
        ),
    ]
