# Generated by Django 5.1.3 on 2024-11-22 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegionStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=100)),
                ('male_percentage', models.FloatField()),
                ('female_percentage', models.FloatField()),
                ('average_age', models.FloatField()),
                ('marital_status_distribution', models.JSONField()),
                ('children_stats', models.JSONField()),
                ('benefits_stats', models.JSONField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
