# Generated by Django 5.1.3 on 2024-11-23 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demographic_analytics', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RegionStatistics',
        ),
    ]
