# Generated by Django 5.1.3 on 2024-11-25 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('demographic_analytics', '0002_delete_regionstatistics'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField(auto_now_add=True, verbose_name='Время действия')),
                ('action_type', models.CharField(max_length=255, verbose_name='Тип действия')),
                ('function_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Используемая функция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Действие пользователя',
                'verbose_name_plural': 'Действия пользователей',
                'ordering': ['-action_time'],
            },
        ),
    ]
